"""Add taglatest table

Revision ID: 02f273e2013b
Revises: 9d0f72ba59c4
Create Date: 2026-04-08 17:05:55.489487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f273e2013b'
down_revision: Union[str, Sequence[str], None] = '9d0f72ba59c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taglatest',
    sa.Column('tagid', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valuenumeric', sa.Float(), nullable=True),
    sa.Column('valuetext', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tagid'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tagid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taglatest')
    # ### end Alembic commands ###
