"""Create initial schema

Revision ID: 36535051fa2d
Revises: 
Create Date: 2026-01-27 23:07:22.869767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36535051fa2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('assettype', sa.String(length=50), nullable=True),
    sa.Column('plcid', sa.String(length=100), nullable=True),
    sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('createdat', sa.DateTime(), nullable=False),
    sa.Column('updatedat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('assetid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('sourcepath', sa.String(length=500), nullable=True),
    sa.Column('sourcetype', sa.String(length=50), nullable=True),
    sa.Column('sourceaddress', sa.Integer(), nullable=True),
    sa.Column('minvalue', sa.Float(), nullable=True),
    sa.Column('maxvalue', sa.Float(), nullable=True),
    sa.Column('aggregationmethod', sa.String(length=50), nullable=True),
    sa.Column('tag_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('createdat', sa.DateTime(), nullable=False),
    sa.Column('updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assetid'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tagid', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valuenumeric', sa.Float(), nullable=True),
    sa.Column('valuetext', sa.Text(), nullable=True),
    sa.Column('valueraw', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('reading_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('testtable')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_table_pkey'))
    )
    op.create_table('testtable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('testtable_pkey'))
    )
    op.drop_table('readings')
    op.drop_table('tags')
    op.drop_table('assets')
    # ### end Alembic commands ###
