"""Add readings indexes

Revision ID: 9d0f72ba59c4
Revises: 36535051fa2d
Create Date: 2026-04-08 16:26:37.122877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0f72ba59c4'
down_revision: Union[str, Sequence[str], None] = '36535051fa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_readings_tag_time', 'readings', ['tagid', 'time'], unique=True)
    op.create_index('idx_readings_time', 'readings', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_readings_time', table_name='readings')
    op.drop_index('idx_readings_tag_time', table_name='readings')
    # ### end Alembic commands ###
